# Base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose FastAPI port
EXPOSE 9001

# Run FastAPI app
CMD ["uvicorn", "src.inference_pipeline.inferencepipeline:app", "--host", "0.0.0.0", "--port", "9001"]