name: MLOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"  # Weekly monitoring

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Training Pipeline
      run: python trainingpipeline.py

    - name: Run Monitoring Pipeline
      run: python monitoringpipeline.py

    - name: Build Docker Image
      run: docker build -t student-productivity-api .

    - name: Push Docker Image
      run: echo "Skipping push to Docker Hub for now"